In [2]:
import numpy as np

In [10]:
A = np.array([1,2,3])
B = np.array([4,3,0])

In [16]:
print("A+B = ",np.add(A,B))
print("A-B = ",np.subtract(A,B))
print(np.multiply(A,B))
print(A*B)

A+B =  [5 5 3]
A-B =  [-3 -1  3]
[4 6 0]
[4 6 0]


In [17]:
C = np.array([[1,2,3],[1,1,1]])
D = np.array([[4,3,9,9],[1,1,2,2],[4,2,1,1]])
print(np.dot(C,D))
print(np.matmul(C,D))

[[18 11 16 16]
 [ 9  6 12 12]]
[[18 11 16 16]
 [ 9  6 12 12]]
